name: Dart Package CD

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify version matches tag
        run: |
          VERSION=$(grep '^version:' pubspec.yaml | awk '{print $2}')
          TAG=${GITHUB_REF#refs/tags/v}

          if [ "$VERSION" != "$TAG" ]; then
            echo "Tag version ($TAG) does not match pubspec.yaml ($VERSION)"
            exit 1
          fi

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get

      - name: Publish package
        run: dart pub publish -f
